### ISSUE TITLE
No line showing in plot

### ISSUE THREAD

**Issue by Davidswa** [Davidswa/SerialTestProject#1]
A plot with auto-scaling axes with reasonable values successfully displays, however no line displays on the plot.

**Comment by bbradbury** [comment]
https://github.com/Davidswa/SerialTestProject/blob/master/src/root/nested/SerialDisplay.py#L35

Currently the serial port data is only read once every 20 seconds when the loop turns over-- is that a safe assumption to make? Seems like data would be available more quickly than that yeah?

**Comment by Davidswa** [comment]
It is not a safe assumption, but I assumed it would just "miss" that data. I think using the animation.FuncAnimation is the wrong idea. I'm going to try and use a loop that waits for the serial to update then clears and replots the graph.

**Comment by Davidswa** [comment]
This original issue has been "solved" in that I was able to get something to plot slowly. I'll open a new issue for my current issues.
